connectors:
 - in_port_name: nanoKONTROL2:nanoKONTROL2 nanoKONTROL2 _ CTR
   in_channel: 0
   out_port_name: Midihub MH-0Q23ZT8:Midihub MH-0Q23ZT8 MIDI 1
   out_channel: 1
 - in_port_name: Arturia KeyStep 32:Arturia KeyStep 32 MIDI 1
   in_channel: 0
   out_port_name: Elektron Model:Cycles
   out_channel: 0