bpm: 100
clock:
 - out_port_name: Midihub 1
instruments:
 - name: drums
   pattern_type: drum
   port: Midihub 1
   channel: 1
   defaults:
     symbols:
      - symbol: '.'
        velocity: 0
      - symbol: '*'
        velocity: 40
      - symbol: x
        velocity: 60
      - symbol: X
        velocity: 100
      - symbol: '!'
        velocity: 120        
   timbres:
     - name: kick
       note: 36
     - name:  snare
       note: 38
     - name: ride
       note: 51
parts:
 - name: drums
   instrument: drums
   denominator: 8
   patterns:
     kick:  x . . . x . . . 
     snare: . . x . . . x . 
     ride:  x . x . x . x . 
