bpm: 120
connectors:
 - in_port_name: nanoKontrol
   in_channel: 0
   out_port_name: Midihub 1
   out_channel: 1
 - in_port_name: keystep
   in_channel: 0
   out_port_name: Cycles
   out_channel: 0
 - in_port_name: keystep
   in_channel: 1
   out_port_name: Cycles
   out_channel: 1
sequence_tracks:
  - name: 'Snare'
    note: 30
    velocity: 100
    denominator: 4
    port: 'Cycles'
    channel: 1
    pattern: '.x.x'
  - name: 'Kick'
    note: 30
    velocity: 100
    denominator: 4
    port: 'Cycles'
    channel: 0
    pattern: 'x.x.'
  - name: 'closed hat'
    note: 30
    velocity: 100
    denominator: 16
    port: 'Cycles'
    channel: 2
    pattern: 'x.x.x.x.x.x.x.x.x.x.x.x.x.xxx.x.'
