bpm: 160
clock:
 - out_port_name: Midihub 1
instruments:
 - name: drums
   port: Midihub 1
   channel: 1
   note_map:
     - name: kick
       note: 36
       symbol: k
     - name:  snare
       note: 38
       symbol: s
     - name: ride
       note: 51
       symbol: r
sequence_tracks:
 - name: Kick
   sequence_type: drum
   denominator: 4
   note_number: 36
   velocity: 80
   pattern: x.x.
   port: Midihub 1
   channel: 1
 - name: Snare
   sequence_type: drum
   denominator: 4
   note_number: 38
   velocity: 100
   pattern: .x.x
   port: Midihub 1
   channel: 1
 - name: HHC
   sequence_type: drum
   denominator: 4
   note_number: 51
   pattern: xxxx
   velocity: 50
   port: Midihub 1
   channel: 1
