bpm: 120
connectors:
 - in_port_name: nanoKontrol
   in_channel: 0
   out_port_name: Midihub 1
   out_channel: 1
 - in_port_name: keystep
   in_channel: 0
   out_port_name: Cycles
   out_channel: 0
 - in_port_name: keystep
   in_channel: 1
   out_port_name: Cycles
   out_channel: 1