bpm: 20
clock:
 - out_port_name: microKorg
connectors:
 - in_port_name: nanoKontrol
   in_channel: 0
   out_port_name: Midihub 1
   out_channel: 1
 - in_port_name: keystep
   in_channel: 0
   out_port_name: Cycles
   out_channel: 0
 - in_port_name: keystep
   in_channel: 1
   out_port_name: Cycles
   out_channel: 1
 - in_port_name: keystep
   in_channel: 2
   out_port_name: microKorg
   out_channel: 0
sequence_tracks:
  - name: 'pad'
    denominator: 8
    port: 'microKorg'
    channel: 0
    pattern: 'xxxxx.x.'
    key: C#
    scale: dorian
    lowest_octave: 4
    highest_octave: 4
    gate_length: 2
  - name: 'base'
    denominator: 2
    port: 'microKorg'
    channel: 0
    pattern: 'xx'
    key: C#
    scale: dorian
    lowest_octave: 1
    highest_octave: 1
    gate_length: 1
  - name: 'top'
    denominator: 2
    port: 'microKorg'
    channel: 0
    pattern: 'xx'
    key: C#
    scale: dorian
    lowest_octave: 5
    highest_octave: 5
    gate_length: 1

  # - name: 'Kick'
  #   note: 30
  #   velocity: 100
  #   denominator: 4
  #   port: 'Cycles'
  #   channel: 0
  #   pattern: 'x.x.'
  # - name: 'closed hat'
  #   note: 30
  #   velocity: 100
  #   denominator: 16
  #   port: 'Cycles'
  #   channel: 2
  #   pattern: 'x.x.x.x.x.x.x.x.x.x.x.x.x.xxx.x.'
