bpm: 120
clock:
 - out_port_name: UX16
 - out_port_name: WIDI Jack
sequence_tracks:
  - name: 'pad'
    type: random
    note_provider:
      type: scale
      key: C#
      mode: dorian
      lowest_octave: 4
      highest_octave: 4
    timing:
      denominator: 8
      gate_length: 2
      pattern: 'xxxxx...'
    port: WIDI Jack
    channel: 0
