[project]
name = "blue-is-beautiful"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mido>=1.3.2",
    "python-rtmidi>=1.5.8",
    "pyyaml>=6.0.2",
    "sortedcontainers>=2.4.0",
    "textual>=0.79.1",
]
